name: Manual workflow
on:
  workflow_dispatch:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Test compile
    - uses: actions/setup-java@v4.7.0
    - run: mkdir ./out/
    - run: javac -cp ./out/ *.java
