name: Manual workflow
on:
  workflow_dispatch:
jobs:
  compile:
    name: Test compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4.7.0
      with:
        distribution: 'temurin'
        java-version: 21
    - run: mkdir ./out/
    - run: javac -cp ./out/ *.java
