name: Verify that the app compiles
on:
  [push, pull_request]
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4.7.0
      with:
        distribution: 'temurin'
        java-version: 21
    - run: mkdir ./out/
    - run: javac -cp ./out/ *.java
